export const VASTMINT_NFT_ADDRESS =
  process.env.NEXT_PUBLIC_NFT_ADDRESS ?? "";

export const VASTMINT_FACTORY_ADDRESS =
  process.env.NEXT_PUBLIC_FACTORY_ADDRESS ?? "";

export const VASTMINT_MARKETPLACE_ADDRESS =
  process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS ?? "";

export const RITUAL_ORACLE_ADDRESS =
  "0xd16C7e0c83e8b304976BBBb4b9ed6cC8c70d656F";

export const RITUAL_CHAIN_ID = 1979;