export const VASTMINT_NFT_ADDRESS =
  process.env.NEXT_PUBLIC_NFT_ADDRESS ?? "";

export const VASTMINT_FACTORY_ADDRESS =
  process.env.NEXT_PUBLIC_FACTORY_ADDRESS ?? "";

export const VASTMINT_MARKETPLACE_ADDRESS =
  process.env.NEXT_PUBLIC_MARKETPLACE_ADDRESS ?? "";

export const RITUAL_CHAIN_ID = 1979;
